### ISSUE TITLE
support vendor prefixed values

### ISSUE THREAD

**Issue by jjenzz** [tokenami/tokenami#103]
browserlist covers vendor prefixing for properties, but values are harder given they're passed as CSS vars.

stylex solves this with [a `firstThatWorks` API](https://github.com/facebook/stylex/tree/main/packages/stylex#stylexfirstthatworks).

**Comment by jjenzz** [comment]
i've looked into the `firstThatWorks` api and it does what i presumed—that is, it relies on the browser to fallback correctly by turning `firstThatWorks(['-wekit-sticky', 'fixed'])` into the following CSS:

```css
.kij2323 {
  position: fixed;
  position: -webkit-sticky;
}
```

unfortunately, this wouldn't work if those values came from the theme because invalid CSS vars fallback to `initial` which is a valid value in all browsers:

```css
.kij2323 {
  position: var(--fixed);
  position: var(--sticky);
}
```

while it is unlikely this specific example would come from theme, i'm unsure what other values might given how customisable the tokenami theme is. i'm going to think some more on this but not sure how possible it is to support anything other than what StyleX does at this stage.
