### ISSUE TITLE
Custom color type checking not working

### ISSUE THREAD

**Issue by derekr** [tokenami/tokenami#132]
I could be declaring this incorrectly, but it seems like the custom theme vars aren't generating correctly? Tried restarting tokenami process manually and reloading the ts server in vscode. The actual css is being produced and works as expected.

![image](https://github.com/tokenami/tokenami/assets/22249/a15d366f-e874-4b7f-991b-79adba8c5cd7)

```css
:root {
  --grid: .25rem;
  --color-slate-100: #f1f5f9;
}

* {
  --margin-bottom: ;
  --background-color: ;
}

[style*="--background-color:"] {
  background-color: var(--background-color);
}

[style*="--margin-bottom:"] {
  margin-bottom: calc(var(--grid) * var(--margin-bottom));
}

[style*="--margin-bottom:var"], [style*="--margin-bottom: var"] {
  margin-bottom: var(--margin-bottom);
}
```
