### ISSUE TITLE
only generate `var` selectors for `grid` properties when used

### ISSUE THREAD

**Issue by jjenzz** [tokenami/tokenami#183]
at the moment, if a property is mapped to `grid` in theme, e.g. `padding`, the stylesheet will generate the following when `--padding` is used:

```css
[style*="--padding:"] {
  padding: calc(var(--grid) * var(--padding));
}

[style*="--padding:var"],[style*="--padding: var"] {
  padding: var(--padding);
}
```

this allows you to use `--padding: 4` for multiples of grid, or `--padding: var(---, 20px)`, or `--padding: var(--space_sm)` if you configure padding to map to a `space` scale.

this works well, however in an effort to keep stylesheet small, i'd like to only generate the `calc` if `--padding: number` is actually used, and only generate the `[style*="--padding:var"]` rules if `--padding: var(...)` is used.
