### ISSUE TITLE
reduce `::selection` output

### ISSUE THREAD

**Issue by jjenzz** [tokenami/tokenami#411]
## Problem 

only certain CSS properties can be used with `::selection` (from [mdn](https://developer.mozilla.org/en-US/docs/Web/CSS/::selection#allowable_properties)):

1. [color](https://developer.mozilla.org/en-US/docs/Web/CSS/color)
2. [background-color](https://developer.mozilla.org/en-US/docs/Web/CSS/background-color)
3. [text-decoration](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration) and its associated properties
4. [text-shadow](https://developer.mozilla.org/en-US/docs/Web/CSS/text-shadow)
5. [-webkit-text-stroke-color](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-stroke-color), [-webkit-text-fill-color](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-fill-color) and [-webkit-text-stroke-width](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-stroke-width)

so, it doesn't make sense to set up the base rules for all properties with this selector. even more so because `::selection` [isn't supported in iOS](https://caniuse.com/?search=%3A%3Aselection) so we end up with duplicated blocks (we can't chain the selector otherwise those styles would break in iOS):

```css
@layer tk1 {
  [style], [style]:after {
    border-radius: var(--border-radius, revert-layer);
    transition: var(--transition, revert-layer);
    color: var(--color, revert-layer);
    font: var(--font, revert-layer);
    min-height: var(--_lmglzt, var(--min-height, revert-layer));
    --_lmglzt: var(--min-height__calc) calc(var(--min-height) * var(--_grid));
    display: var(--display, revert-layer);
    text-align: var(--text-align, revert-layer);
  }

  [style*="selection_"]::selection {
    border-radius: var(--border-radius, revert-layer);
    transition: var(--transition, revert-layer);
    color: var(--color, revert-layer);
    font: var(--font, revert-layer);
    min-height: var(--_lmglzt, var(--min-height, revert-layer));
    --_lmglzt: var(--min-height__calc) calc(var(--min-height) * var(--_grid));
    display: var(--display, revert-layer);
    text-align: var(--text-align, revert-layer);
  }
}
```

## Proposed change

treat `::selection` as more of a special case than we already do so that we only generate styles for properties it supports:

```css
@layer tk1 {
  [style], [style]:after {
    border-radius: var(--border-radius, revert-layer);
    transition: var(--transition, revert-layer);
    color: var(--color, revert-layer);
    font: var(--font, revert-layer);
    min-height: var(--_lmglzt, var(--min-height, revert-layer));
    --_lmglzt: var(--min-height__calc) calc(var(--min-height) * var(--_grid));
    display: var(--display, revert-layer);
    text-align: var(--text-align, revert-layer);
  }

  [style*="selection_"]::selection {
    color: var(--color, revert-layer);
  }
}
```
