### ISSUE TITLE
add `@supports` support

### ISSUE THREAD

**Issue by jjenzz** [tokenami/tokenami#45]

**Comment by jjenzz** [comment]
this is possible via a custom selector e.g

```tsx
{
  selectors: {
    'supports-flex': ['@supports (display: flex)', '&'],
  }
}
```

this will generate something similar to the following when used:

```css
@supports (display: flex) {
  [style*="--supports-flex_display:"] {
    display: var(--supports-flex_display, var(--display));
  }
}
```
