### ISSUE TITLE
configurable selectors

### ISSUE THREAD

**Issue by jjenzz** [tokenami/tokenami#66]
atm we have a `media` property in config and predefined pseudo classes/selectors that authors can use as _variants_ for their token properties, e.g. `---md_`, `---hover_`, etc. 

this ticket is to explore whether we can have a `selectors` property in config instead with recommended defaults (`hover`, etc.) but consumers can customise, for instance:

```jsx
{
  selectors: {
    md: '@media (min-width: 700px)',
    lg: '@media (min-width: 1024px)',
    hover: '&:hover',
    focus: '&:focus',
    'prev-checked': ':checked + &',
  },
}
```

which would generate something like:

```css
[style~="---hover_pl:"]:hover {
  padding-left: var(---hover_pl);
}

:checked + [style~="---prev-checked_pl:"] {
  padding-left: var(---prev-checked_pl);
}
```
