### ISSUE TITLE
reduce generated css for matching chained selectors

### ISSUE THREAD

**Issue by jjenzz** [tokenami/tokenami#79]
at the moment if we add `--hover_active-color` and `--active_hover-color` we'll have two separate atomic rules in stylesheet:

```css
[style*="--hover_active_color:"]:active:hover {
  color: var(--hover_active_color, var(--color));
}

[style*="--active_hover_color:"]:hover:active {
  color: var(--active_hover_color, var(--color));
}
```

need to think of a way to help consumers avoid this bcos types wld get pretty slow if i relied on typescript here. perhaps an eslint plugin could encourage specificity order to match selectors config order.
