### ISSUE TITLE
use `@property` ?

### ISSUE THREAD

**Issue by jjenzz** [tokenami/tokenami#8]
not sure if this is good idea yet or not but something to explore:

```css
@property --padding {
  syntax: "<number>";
  inherits: false;
  initial-value: 0;
}

@property --color {
  syntax: "<color>";
  inherits: true;
  initial-value: currentColor;
}

@property --background-color {
  syntax: "<color>";
  inherits: false;
  initial-value: transparent;
}
```
